In [180]:
#imports NumPy library
import numpy as np

In [181]:
#initializes [1,2,3,4,5] to the variable python_list , prints python_list, prints the variable type for python_list 
python_list = [1, 2, 3, 4, 5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [182]:
#initializes [5,4,3,2,1] to the variable python_list2 , prints python_list2, prints the variable type for python_list2 
python_list2 = [5, 4, 3, 2, 1]
print(python_list2)
print(type(python_list2))

[5, 4, 3, 2, 1]
<class 'list'>


In [183]:
#intializes the same list from python_list  to variable numpy_array,
#prints the contents of the numpy array, and prints the type for the variable
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [184]:
#intializes the same list from python_list2  to variable numpy_array,
#prints the contents of the numpy array, and prints the type for the variable
numpy_array = np.array(python_list2)
print(numpy_array)
print(type(numpy_array))

[5 4 3 2 1]
<class 'numpy.ndarray'>


In [185]:
#intializes a 2d aray to a variable, prints its contents, and type for the variable
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [186]:
#intializes a 2d aray to a variable, prints its contents, and type for the variable
python_2d_array2 = [[5, 4, 3, 4, 5], [6, 9, 8, 9, 10]]
print(python_2d_array2)
print(type(python_2d_array2))

[[5, 4, 3, 4, 5], [6, 9, 8, 9, 10]]
<class 'list'>


In [187]:
#initializes the same 2d array from python_2d_array to variable numpy_2d_array,
#prints the contents of the numpy_2d_array, and prints the type for the variable
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [188]:
#initializes the same 2d array from python_2d_array to variable numpy_2d_array,
#prints the contents of the numpy_2d_array, and prints the type for the variable
numpy_2d_array = np.array(python_2d_array2)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 5  4  3  4  5]
 [ 6  9  8  9 10]]
<class 'numpy.ndarray'>


In [189]:
#we can see from our above code that initializing lists and arrays in NumPy are considered different types by Python

In [190]:
#this outputs all the numbers 0<=x<15 with a default stepsize of 1
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [191]:
#this outputs all the numbers 0<=x<100 with a default stepsize of 1
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [192]:
#this outputs all the numbers 0<=x<15 with a stepsize of 2
np.arange(0, 15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [193]:
#this outputs all the numbers 0<=x<100 with a stepsize of 2
np.arange(0, 100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [194]:
#this outputs all the numbers 0<=x<15 with a default stepsize of 1
#outputted in 3 arrays with 5 elements 
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [195]:
#this outputs all the numbers 0<=x<100 with a default stepsize of 2
#outputted in 3 arrays with 5 elements 
np.arange(0, 10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [196]:
#outputs an array with 15 0's
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
#outputs an array with 100 0's
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [198]:
#outputs an array of 15 0's 
#outputted in 3 arrays with 5 elements
np.zeros(15).reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [199]:
#outputs an array of 15 0's 
#outputted in 2 arrays with 50 elements
np.zeros(100).reshape(2, 50)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [200]:
#outputs an array of 15 1's
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [201]:
#outputs an array of 10 1's
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [202]:
#outputs an array of 15 1's
#outputted in 3 arrays with 5 elements
np.ones(15).reshape(3, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [203]:
#outputs an array of 25 1's
#outputted in 5 arrays with 5 elements
np.ones(25).reshape(5, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [204]:
#changes the default type of float for each element to int 
np.ones(15, dtype=int).reshape(3, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [205]:
#changes the default type of float for each element to Complex 
np.ones(15, dtype=complex).reshape(3, 5)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [206]:
#creates an identity matrix of size 5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [207]:
#creates an identity matrix of size 1
np.eye(1)

array([[1.]])

In [208]:
#fills array with 5 random numbers from a uniform distrubtion of [0,1)
np.random.rand(5)

array([0.57343445, 0.35019511, 0.96337155, 0.98584354, 0.46593915])

In [209]:
#fills array with 10 random numbers from a uniform distrubtion of [0,1)
np.random.rand(10)

array([0.66068935, 0.31097175, 0.21605182, 0.98847166, 0.87478213,
       0.51355369, 0.35741669, 0.95748682, 0.89456097, 0.31645132])

In [210]:
#fills array with 5 random numbers from standard normal distribution
np.random.randn(5)

array([ 0.15238754, -1.31023746,  1.42391452,  0.81173318, -1.94205637])

In [211]:
#fills array with 10 random numbers from standard normal distribution
np.random.randn(10)

array([ 0.63605124, -0.09546231, -1.52868068, -1.07540051,  1.00239517,
        0.14682818,  0.98757699, -1.54771091,  1.3838331 , -0.26547375])

In [212]:
# returns a random integer between 1 and 100
np.random.randint(1,100)

93

In [213]:
# returns a random integer between 1 and 1000000
np.random.randint(1,1000000)

807644

In [214]:
#return an array of size 15 with random integers between 1 and 100
np.random.randint(1, 100, 15)

array([50, 90, 55, 33, 34, 67, 56, 67, 38, 65, 20, 10, 98, 11, 45])

In [215]:
#return an array of size 15 with random integers between 1 and 1000000
np.random.randint(1, 1000000, 15)

array([ 20288, 807435, 838874, 664992, 820426, 904311, 305122, 654082,
       473910, 858543, 748797, 235996, 111510, 645558, 475201])

In [216]:
#returns 4 arrays with 5 elements with random integers between 0 and 100
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[37, 46, 29, 46, 62],
       [16, 96, 65,  2, 54],
       [29, 25, 11, 77, 63],
       [41, 94, 51, 11, 24]])

In [217]:
#self explanatory
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 2, and is a located at position 8
The largest value in A is 96, and is a located at position 6


In [218]:
#returns 4 arrays with 5 elements with random integers between 0 and 1000
B = np.random.randint(0, 1000, 200).reshape(5, 40)
B

array([[430, 408, 812, 248, 402, 190, 240, 699, 109, 870,  21, 331, 377,
        329,   8,  74, 483, 550, 743, 636, 954, 850, 921, 452, 952, 746,
        732, 696, 358, 553, 131, 422, 263, 690, 718, 777, 254,  49, 812,
        725],
       [ 23, 916, 697, 551, 857, 415, 466, 149, 505, 146, 669, 380, 234,
        156, 442, 773, 189, 713, 461, 138, 852, 786, 975, 984, 435, 732,
        207, 483, 612, 351, 402, 859, 957, 229, 378, 627, 156,  16, 826,
        477],
       [874, 866, 850,  88, 605, 871, 879, 292, 457, 134, 105, 137, 326,
        179, 291, 378, 554, 108, 941, 174, 559, 935, 531, 206, 924, 850,
        190, 850, 346, 118, 797,  50, 386, 609, 358, 292, 316, 634, 331,
         15],
       [693, 494, 911, 119, 375, 964, 483, 654, 371, 811, 243, 877,  76,
         39, 904, 557, 888, 395,  33, 390, 479, 110, 803,  25, 398, 969,
        581, 260, 771, 380, 513, 459, 523, 855, 999, 624, 166, 712, 233,
        848],
       [374, 660, 198, 824, 867, 616, 285, 234, 990, 701, 422, 825, 

In [219]:
#self explanatory
print(f'The smallest value in A is {B.min()}, and is a located at position {B.argmin()}')
print(f'The largest value in A is {B.max()}, and is a located at position {B.argmax()}')

The smallest value in A is 8, and is a located at position 14
The largest value in A is 999, and is a located at position 154


In [220]:
#returns the dimensions of the 2d-array A
A.shape

(4, 5)

In [221]:
#returns the dimensions of the 2d-array B
B.shape

(5, 40)

In [222]:
#returns the dimensions of the 2d-array A
np.shape(A)

(4, 5)

In [223]:
#returns the dimensions of the 2d-array B
np.shape(B)

(5, 40)

In [224]:
#example arrays we will be using to practice some operations
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [225]:
#result of adding A and B
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [226]:
#result of adding A and B twice
A + B + B

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73])

In [227]:
#adds 5 to each element in array A
A+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [228]:
#adds 10 to each element in array A
A+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [229]:
#result of subtracting B from A
A - B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [230]:
#result of subtracting B twice from A
A - B - B

array([ -1,  -4,  -7, -10, -13, -16, -19, -22, -25, -28, -31, -34, -37,
       -40, -43])

In [231]:
#subtracts 5 from each element in array A
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [232]:
#subtracts 100 from each element in array A
A - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90, -89, -88, -87,
       -86, -85])

In [233]:
#multiplies A and B
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [234]:
#multiplies A and B and adds to 2*B
A * B + 2*B

array([  3,  12,  25,  42,  63,  88, 117, 150, 187, 228, 273, 322, 375,
       432, 493])

In [235]:
#divides A by B
A/B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [236]:
#divides A by B and subtracts it from A*B
A*B-A/B

array([  0.        ,   5.33333333,  14.4       ,  27.42857143,
        44.44444444,  65.45454545,  90.46153846, 119.46666667,
       152.47058824, 189.47368421, 230.47619048, 275.47826087,
       324.48      , 377.48148148, 434.48275862])

In [237]:
#this performs matrix multiplication
np.matmul(C, D)

array([[ 2,  3],
       [ 6, 11]])

In [238]:
#this performs matrix multiplication
np.matmul(D, C)

array([[ 2,  3],
       [ 6, 11]])

In [239]:
#sqrts each element in matrix E
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [240]:
#sqrts the sqrt of each element in matrix E
np.sqrt(np.sqrt(E))

array([[1.        , 1.18920712, 1.31607401, 1.41421356, 1.49534878],
       [1.56508458, 1.62657656, 1.68179283, 1.73205081, 1.77827941],
       [1.82116029, 1.86120972, 1.89882892, 1.93433642, 1.96798967]])

In [241]:
#log of each elements in matrix E
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [242]:
#logs the log of each elements in array A
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ])

In [243]:
#if the number is even we return -1, else we multiply it by 100
np.where(F%2==0, -1, F*100)

array([ -1, 100,  -1, 300,  -1, 500,  -1, 700,  -1, 900,  -1])

In [244]:
#if the number is odd we return -1, else we multiply it by 100
np.where(F%2==1, -1, F*100)

array([   0,   -1,  200,   -1,  400,   -1,  600,   -1,  800,   -1, 1000])

In [245]:
#recall that counting starts from 0 not 1
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [246]:
#recall that counting starts from 0 not 1
B = np.arange(100)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [247]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


In [248]:
print(f'B[0]: {B[0]}')
print(f'B[50]: {B[50]}')
print(f'B[99]: {B[99]}')

B[0]: 0
B[50]: 50
B[99]: 99


In [249]:
#returns all elements from index 0 to 9 (the stop index is not inclusive)
A[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [250]:
#returns all elements from index 0 to 15 (the stop index is not inclusive)
A[0:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [251]:
#converts all elements from index 0 to 9 to 500
A[0:10] = 500
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

In [252]:
#converts all elements from index 10 to 15 to 500
A[10:15] = 100
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 100, 100, 100,
       100, 100])

In [253]:
#example we will use to practice indexing 2d-arrays
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [254]:
#example of returning a specific position in 2d-array
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


In [255]:
#example of returning a specific position in 2d-array
print(f'1th row and 5nd col in B: {B[1, 5]}')
print(f'4rd row and 4rd col in B: {B[4, 4]}')
print(f'2th row and 2nd col in B: {B[2, 2]}')

1th row and 5nd col in B: 15
4rd row and 4rd col in B: 44
2th row and 2nd col in B: 22


In [256]:
#returns elemnts in rows 0-2 and columns 3-5
B[0:2, 3:5]

array([[ 3,  4],
       [13, 14]])

In [257]:
#returns elemnts in rows 0-2 and columns 3-5
B[2:4, 0:1]

array([[20],
       [30]])

In [258]:
#converts elemnts in rows 0-2 and columns 3-5 to -1
B[0:2, 3:5] = -1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, 12, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [259]:
#converts elemnts in rows 1-4 and columns 2-5 to -1
B[1:4, 2:5] = -1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, -1, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, -1, -1, -1, 25, 26, 27, 28, 29],
       [30, 31, -1, -1, -1, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [260]:
#example we will use to practice boolean array indexing
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [261]:
#returns true if element is even and false otherwise
C%2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [262]:
#returns true if element is odd and false otherwise
C%2 == 1

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [263]:
#sum all even elements
(C%2 == 0).sum()

25

In [264]:
#sum all odd elements
(C%2 == 1).sum()

25

In [265]:
#returns an array of only even elements
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [266]:
#returns an array of only even elements
C[C%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])